/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package server;

import org.junit.Test;
import org.springframework.boot.test.context.SpringBootTest;


@SpringBootTest
public class AppTest {

	@Test
	public void contextLoads() {
	}

}

